config/routes.rb
Rails.application.routes.draw do

  get 'inicio' => 'home#inicio', as: :index

  get 'localizacion' => 'home#localizacion', as: :localizacion

  get 'contacto' => 'home#contacto', as: :contacto
  post 'contacto' => 'home#contacto'

  root 'home#inicio'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :peticiones


	def peticiones
	  	valor = (cookies[:peticiones] || '0').to_i
	  	cookies[:peticiones] =  { :value => (valor + 1).to_s, :expires => Time.now + 1.hour }
	  	@peticiones = cookies[:peticiones]
	end

end

app/controllers/home_controller.rb
#encoding: utf-8
class HomeController < ApplicationController

  def inicio
  	@titulo = 'Bienvenido a mi proyecto - PCV'
  end

  def localizacion
  	@titulo = "Localización - PCV"
  	@latitude = 38.164375
  	@longitude = -0.472782
  end

  def contacto
  	@titulo = "Contacto - PCV"

    if request.post?
      begin
        peticiones = cookies[:peticiones] || 0
        if Email.mail_admin(params, peticiones).deliver
          if Email.mail_contacto(params).deliver
            flash.now[:noticia] = 'El email ha sido enviado correctamente'
          else
            flash.now[:error] = 'No hemos podido enviarte la confirmación del envío de contacto.'
          end
        else
          flash.now[:error] = 'Se ha producido un error al enviar el mail de contacto.'
        end
      rescue
         flash.now[:error] = 'No se ha podido enviar el email de contacto.'
      end

    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def enlace_imagen imagen, size, path, clase
		link_to (image_tag imagen, :size => size), path, :class => clase
	end


  def is_active path
     'class=active' if current_page? path
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def static_map latitude, longitude
    params = {
      :center => [latitude, longitude].join(","),
      :zoom => 16,
      :size => "500x350",
      :markers => [latitude, longitude].join(","),
      :sensor => true
      }
 
    query_string =  params.map{|k,v| "#{k}=#{v}"}.join("&")
    image_tag "http://maps.googleapis.com/maps/api/staticmap?#{query_string}"
  end


  def link_ver_detalles(url)
    link_to 'Ver detalles »', url, target:'blank', class: 'btn btn-default', role: 'button'
  end
end

app/views/home/contacto.html.erb
<h1><%= @titulo %></h1>


<div class="col-md-offset-3 col-md-6">
	<%= form_tag('', role: 'form')   do %>
		<div class="form-group">
			<%= label 'nombre', "Nombre",  for: 'nombre' %>
			<%= text_field_tag 'nombre', nil, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= label 'email', "Email",  for: 'email' %>
			<%= email_field_tag 'email', nil, class: 'form-control'  %>
		</div>
		<div class="form-group">
			<%= label 'asunto', "Asunto", for: 'asunto' %>
			<%= text_field_tag 'asunto', nil, class: 'form-control'  %>
		</div>
		<div class="form-group">
			<%= label_tag'mensaje', "Mensaje", for: 'mensaje' %>
			<%= text_area_tag 'mensaje', nil, :size=>'25x10', class: 'form-control'  %>		
		</div>
		<%= submit_tag 'Enviar', class: 'btn btn-default' %>
	<% end %>
</div>

app/views/home/inicio.html.erb
<h1><%= @titulo %></h1>
<div class="row">
	<div class="col-md-10 col-md-offset-2">
		<%= image_tag 'banner.jpg', size: '700x150' %>
	</div>
</div>
<div class="row" id='servicios'>
    <div class="col-lg-4">
      <%= image_tag 'rails.jpeg', size: '140x140', alt: 'Rails' %>
      <h2>Rails</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque possimus, provident hic suscipit quae doloribus nobis libero cupiditate magnam officiis, laborum. Totam iure laudantium excepturi obcaecati, numquam eligendi quisquam doloribus.</p>
      <p><%= link_ver_detalles 'http://rubyonrails.org/' %></p>
    </div>
    <div class="col-lg-4">
       <%= image_tag 'heroku.jpeg', size: '140x140', alt: 'Heroku' %>
      <h2>Heroku</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veniam deserunt eveniet iusto voluptatem repellendus molestiae, vitae earum fugit harum pariatur illo, quibusdam perferendis possimus cupiditate sed ducimus, animi! Nihil, veritatis!</p>
      <p><%= link_ver_detalles 'https://www.heroku.com/' %></p>
    </div>
    <div class="col-lg-4">
       <%= image_tag 'github.jpeg', size: '140x140', alt: 'Github' %>
      <h2>Github</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et in ratione eaque ut repellendus laudantium dicta dolore perspiciatis quo neque quidem quod cupiditate praesentium, cumque, laboriosam quasi tenetur ab rerum.</p>
      <p><%=  link_ver_detalles 'http://www.github.com'%></p>
    </div>
</div>

app/views/home/localizacion.html.erb
<h1><%= @titulo %></h1>


<div class="col-md-6">
	<%= static_map @latitude, @longitude %>  
</div>
<div class="col-md-6">
	<address>
	  <strong>Antonio, SA.</strong><br>
	  795 Folsom Ave, Suite 600<br>
	  San Francisco, CA 94107<br>
	  <abbr title="Phone">P:</abbr> (123) 456-7890
	</address>

	<address>
	  <strong>Full Name</strong><br>
	  <%= mail_to "first.last@example.com" %>
	</address>
</div>

app/views/layouts/_footer.html.erb
<footer>
	<nav class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
	  <div class="container">
	    <div class="row">
	    	<div class="col-md-6">
	    		&copy; <%= DateTime.now.year %> All Right Reserved
	    	</div>
	    	<div class="col-md-6 right">
	    		Site Designed by Antonio Leal
	    	</div>
	    </div>
	  </div>
	</nav>
<footer>

app/views/layouts/_head.html.erb
 <title><%= @titulo ||= 'PVC Bienvenido' %></title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
 <%= favicon_link_tag 'favicon.ico' %>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	  <div class="container">
		    <!-- Brand and toggle get grouped for better mobile display -->
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <%= enlace_imagen 'rails.png', '30x30', index_path, 'navbar-brand' %>
		    </div>

		   <!-- Collect the nav links, forms, and other content for toggling -->
		    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		      <ul class="nav navbar-nav">
		        <li <%= is_active index_path %>><%= link_to 'Inicio', index_path %> <span class="sr-only">(current)</span></li>
		        <li <%= is_active localizacion_path %>><%= link_to 'Localización', localizacion_path %></li>
		        <li <%= is_active contacto_path %>><%= link_to 'Contacto', contacto_path %></li>
		      </ul>
	  </div>	  	
	</nav>
</header>

app/views/layouts/_mensajes.html.erb
<% if flash[:noticia] %>
	<div class="row">
		<div class="col-md-10 col-md-offset-2">
			<div class="alert alert-success" role="alert">
				<button type="button" class="close" data-dismiss="alert">
				  <span aria-hidden="true">&times;</span>
				  <span class="sr-only">Close</span>
				</button>
			 	<%= flash[:noticia] %>
			</div>
		</div>
	</div>
<% end %>
<% if flash[:error] %>
	<div class="row">
		<div class="col-md-10 col-md-offset-2">
			<div class="alert alert-danger" role="alert">
				<button type="button" class="close" data-dismiss="alert">
				  <span aria-hidden="true">&times;</span>
				  <span class="sr-only">Close</span>
				</button>
			 	<%= flash[:error] %>
			</div>
		</div>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= render 'layouts/head' %>
</head>
<body>
	<!-- Cabecera -->
		<%= render 'layouts/header' %>
	<!-- Fin Cabecera -->
	<div class="container">
		<%= render 'layouts/mensajes' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>

</body>
</html>